/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux mapfw.ewi.tudelft.nl 5.15.0-73-generic x86_64"
#define LGL_COMPILED "Sun Jun 18 14:35:46 UTC 2023"
#define LGL_RELEASED "Wed Jun  7 15:19:03 CEST 2017"
#define LGL_VERSION "bbe"
#define LGL_ID "d35430ca305be47ff998f3af610579bfa6f1fbac"
