(define (problem problem5) (:domain domain2)
(:objects
	train0  - slt
	train1  - slt
	train2  - sng
	v0 t0 t1 t2 t3 t4 s0 s1  - trackpart
	track0 track1 track2  - track
)
(:init
	(= (timestep) 0)
	(nextTo v0 s0)
	(nextTo s0 v0)
	(nextTo s0 t1)
	(nextTo t1 s0)
	(nextTo s0 s1)
	(nextTo s1 s0)
	(nextTo t1 t2)
	(nextTo t2 t1)
	(nextTo s1 t4)
	(nextTo t4 s1)
	(nextTo s1 t3)
	(nextTo t3 s1)
	(nextTo t3 t0)
	(nextTo t0 t3)
	(free t0)
	(free t1)
	(free t2)
	(free t3)
	(free t4)
	(free s0)
	(switch s0)
	(free s1)
	(switch s1)
	(onTrack t1 track0)
	(onTrack t2 track0)
	(onTrack t4 track1)
	(onTrack t3 track2)
	(onTrack t0 track2)
	(at train0 v0)
	(= (length train0) 3)
	(at train1 v0)
	(= (length train1) 3)
	(at train2 v0)
	(= (length train2) 4)
	(= (arrive train0) 1)
	(= (arrive train1) 3)
	(= (arrive train2) 8)
	(= (arrive train1) 9)
	(= (depart train0) 14)
	(= (depart train1) 5)
	(= (depart train2) 12)
	(= (depart train1) 17)
)
(:goal (and
	(exists (?t - slt) (and (at ?t v0) (<= (depart ?t) 25) (= (length ?t) 3)))
	(exists (?t - slt) (and (at ?t v0) (<= (depart ?t) 25) (= (length ?t) 3)))
	(exists (?t - sng) (and (at ?t v0) (<= (depart ?t) 25) (= (length ?t) 4)))
	(forall (?t - trainunit) (hasBeenParked ?t))
))
)