(define (problem hello1) (:domain domain3)
(:objects
	train1  - slt
	train2  - slt
	train3  - sng
	train4  - virm
	v1 t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 s1 s2 s3  - trackpart
	track1 track2 track3 track4  - track
)
(:init
	(onPath v1)
	(nextTo v1 s3)
	(nextTo s3 v1)
	(nextTo s3 t6)
	(nextTo t6 s3)
	(nextTo s3 s2)
	(nextTo s2 s3)
	(nextTo t6 t3)
	(nextTo t3 t6)
	(nextTo s2 s1)
	(nextTo s1 s2)
	(nextTo s2 t4)
	(nextTo t4 s2)
	(nextTo s1 t9)
	(nextTo t9 s1)
	(nextTo s1 t8)
	(nextTo t8 s1)
	(nextTo t9 t7)
	(nextTo t7 t9)
	(nextTo t8 t10)
	(nextTo t10 t8)
	(nextTo t10 t2)
	(nextTo t2 t10)
	(nextTo t2 t1)
	(nextTo t1 t2)
	(nextTo t4 t5)
	(nextTo t5 t4)
	(free t1)
	(free t2)
	(free t3)
	(free t4)
	(free t5)
	(free t6)
	(free t7)
	(free t8)
	(free t9)
	(free t10)
	(free s1)
	(switch s1)
	(free s2)
	(switch s2)
	(free s3)
	(switch s3)
	(onTrack t6 track1)
	(onTrack t3 track1)
	(onTrack t9 track2)
	(onTrack t7 track2)
	(onTrack t8 track3)
	(onTrack t10 track3)
	(onTrack t2 track3)
	(onTrack t1 track3)
	(onTrack t4 track4)
	(onTrack t5 track4)
	(at train1 v1)
	(at train2 v1)
	(at train3 v1)
	(at train4 v1)
	(= (timestep) 0)
	(= (arrive train1) 1)
	(= (arrive train2) 2)
	(= (arrive train3) 8)
	(= (arrive train4) 11)
	(= (depart train1) 7)
	(= (depart train2) 24)
	(= (depart train3) 21)
	(= (depart train4) 17)
	(= (departed train1) 9)
	(= (departed train2) 26)
	(= (departed train3) 23)
	(= (departed train4) 19)
	(= (length train1) 3)
	(= (length train2) 3)
	(= (length train3) 4)
	(= (length train4) 6)
	(= (capacity track1) 8)
	(= (capacity track2) 8)
	(= (capacity track3) 16)
	(= (capacity track4) 8)
)
(:goal (and
	(exists (?t - slt) (and (at ?t v1) (<= (depart ?t) 8) (= (length ?t) 3)))
	(exists (?t - slt) (and (at ?t v1) (<= (depart ?t) 25) (= (length ?t) 3)))
	(exists (?t - sng) (and (at ?t v1) (<= (depart ?t) 22) (= (length ?t) 4)))
	(exists (?t - virm) (and (at ?t v1) (<= (depart ?t) 18) (= (length ?t) 6)))
	(forall (?t - trainunit) (hasBeenParked ?t))
))
)