(define (problem carouselProblem1) (:domain domain1)
(:objects
   train1 - sng
   train2 - icm
   train3 - virm
   train4 - slt
   v1 v2 v3 v4 t0 t1 t2 t3 t4 t5 - trackpart
   track1 - track
)
(:init
   (at train1 v1)
   (nextTo v1 v2)
   (nextTo v2 v1)
   (at train2 v2)
   (nextTo v2 v3)
   (nextTo v3 v2)
   (at train3 v3)
   (nextTo v3 v4)
   (nextTo v4 v3)
   (at train4 v4)
   (nextTo v1 t0)
   (nextTo t0 v1)
   (nextTo t0 t1)
   (nextTo t1 t0)
   (nextTo t0 t5)
   (nextTo t5 t0)
   (free t0)
   (free t1)
   (nextTo t1 t2)
   (nextTo t2 t1)
   (free t2)
   (nextTo t2 t3)
   (nextTo t3 t2)
   (free t3)
   (nextTo t3 t4)
   (nextTo t4 t3)
   (free t4)
   (nextTo t4 t5)
   (nextTo t5 t4)
   (free t5)
   (onTrack t1 track1)
   (onTrack t2 track1)
   (onTrack t3 track1)
   (onTrack t4 track1)
   (onTrack t5 track1)
   (onPath v1)
   (onPath v2)
   (onPath v3)
   (onPath v4)
   (switch t0)  
)
(:goal (and
   (forall (?t - slt) (or (at ?t v1)))
   (forall (?t - sng) (or (at ?t v4)))
   (forall (?t - virm) (or (at ?t v3)))
   (forall (?t - icm) (or (at ?t v2)))
   (forall (?t - trainunit) (hasBeenParked ?t))
)))
