(define (problem problem0) (:domain domain0)
(:objects
  train1 train2 train3 train4 train5  - trainunit
  v1 v2 v3 v4 v5 t0 t1 t3 t2 t4 t5  - trackpart
  track1 track2 track3  - track
)
(:init
   (at train1 v4)
   (nextTo v1 v2)
   (nextTo v2 v1)
   (at train2 v1)
   (nextTo v2 v3)
   (nextTo v3 v2)
   (at train3 v3)
   (nextTo v3 v4)
   (nextTo v4 v3)
   (at train4 v2)
   (nextTo v4 v5)
   (nextTo v5 v4)
   (at train5 v5)
   (nextTo v1 t0)
   (nextTo t0 v1)
   (nextTo t0 t1)
   (nextTo t1 t0)
   (free t0)
   (free t1)
   (nextTo t1 t3)
   (nextTo t3 t1)
   (free t3)
   (nextTo t0 t2)
   (nextTo t2 t0)
   (free t2)
   (nextTo t2 t4)
   (nextTo t4 t2)
   (free t4)
   (nextTo t0 t5)
   (nextTo t5 t0)
   (free t5)
   (onTrack t1 track1)
   (onTrack t3 track1)
   (onTrack t2 track2)
   (onTrack t4 track2)
   (onTrack t5 track3)
   (= (arrive train1) 4)
   (= (arrive train2) 1)
   (= (arrive train3) 3)
   (= (arrive train4) 2)
   (= (arrive train5) 5)
   (= (depart train1) 5)
   (= (depart train2) 4)
   (= (depart train3) 3)
   (= (depart train4) 2)
   (= (depart train5) 1)
   (= (depth t1) 1)
   (= (depth t2) 1)
   (= (depth t3) 2)
   (= (depth t4) 2)
   (= (depth t5) 1)
)
(:goal (and
   (forall (?t - trainunit) (hasBeenParked ?t))
)))
