(define (problem myproblem) (:domain domain1)
(:objects
    train1 - sng
    train2 - sng
    train3 - sng
    train4 - icm
    train5 - icm
    train6 - icm
    train7 - virm
    train8 - virm
    train9 - virm
    train10 - slt
    train11 - slt
    train12 - slt
    v1 v2 v3 v4 v5 v6 v7 v8 v9 v10 v11 v12 t0 t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16 t17  - trackpart
    track1 track2 track3 track4 track5  - track
)
(:init
    (at train1 v1)
    (nextTo v1 v2)
    (at train2 v2)
    (nextTo v2 v3)
    (at train3 v3)
    (nextTo v3 v4)
    (at train4 v4)
    (nextTo v4 v5)
    (at train5 v5)
    (nextTo v5 v6)
    (at train6 v6)
    (nextTo v6 v7)
    (at train7 v7)
    (nextTo v7 v8)
    (at train8 v8)
    (nextTo v8 v9)
    (at train9 v9)
    (nextTo v9 v10)
    (at train10 v10)
    (nextTo v10 v11)
    (at train11 v11)
    (nextTo v11 v12)
    (at train12 v12)
    (nextTo v1 t0)
    (switch t0)
    (nextTo t0 t1)
    (free t0)
    (free t1)
    (nextTo t1 t2)
    (free t2)
    (nextTo t0 t3)
    (free t3)
    (nextTo t3 t4)
    (free t4)
    (nextTo t4 t5)
    (free t5)
    (nextTo t0 t6)
    (free t6)
    (nextTo t6 t7)
    (free t7)
    (nextTo t7 t8)
    (free t8)
    (nextTo t8 t9)
    (free t9)
    (nextTo t9 t10)
    (free t10)
    (nextTo t10 t11)
    (free t11)
    (nextTo t11 t12)
    (free t12)
    (nextTo t10 t13)
    (free t13)
    (nextTo t13 t14)
    (free t14)
    (nextTo t8 t15)
    (free t15)
    (nextTo t15 t16)
    (free t16)
    (nextTo t16 t17)
    (free t17)
    (onTrack t1 track1)
    (onTrack t2 track1)
    (onTrack t3 track2)
    (onTrack t4 track2)
    (onTrack t5 track2)
    (onTrack t11 track3)
    (onTrack t12 track3)
    (onTrack t13 track4)
    (onTrack t14 track4)
    (onTrack t15 track5)
    (onTrack t16 track5)
    (onTrack t17 track5)
    (onPath v1)
    (onPath v2)
    (onPath v3)
    (onPath v4)
    (onPath v5)
    (onPath v6)
    (onPath v7)
    (onPath v8)
    (onPath v9)
    (onPath v10)
    (onPath v11)
    (onPath v12)
)
(:goal (and
    (exists (?t - virm) (at ?t v4))
    (exists (?t - virm) (at ?t v5))
    (exists (?t - virm) (at ?t v6))
    (exists (?t - sng) (at ?t v10))
    (exists (?t - sng) (at ?t v11))
    (exists (?t - sng) (at ?t v12))
    (exists (?t - icm) (at ?t v7))
    (exists (?t - icm) (at ?t v8))
    (exists (?t - icm) (at ?t v9))
    (exists (?t - slt) (at ?t v1))
    (exists (?t - slt) (at ?t v2))
    (exists (?t - slt) (at ?t v3))
    (hasBeenParked train1)
    (hasBeenParked train2)
    (hasBeenParked train3)
    (hasBeenParked train4)
    (hasBeenParked train5)
    (hasBeenParked train6)
    (hasBeenParked train7)
    (hasBeenParked train8)
    (hasBeenParked train9)
    (hasBeenParked train10)
    (hasBeenParked train11)
    (hasBeenParked train12)
)))
